# Generated by Django 5.1 on 2024-09-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='whatsapp',
        ),
    ]
