# Generated by Django 5.1 on 2024-09-08 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customuser_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(default=1, max_length=14, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato: (11)99999-9999', regex='^\\(\\d{2}\\)\\d{5}-\\d{4}$')]),
            preserve_default=False,
        ),
    ]
