# Generated by Django 5.1 on 2024-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0002_datasabertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbarbeiro',
            name='numero',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
