# Generated by Django 5.1 on 2024-08-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0003_dadosbarbeiro_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(max_length=100)),
                ('valores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barbeiro.valores')),
            ],
        ),
    ]
