# Generated by Django 5.1 on 2024-08-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0004_valores_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbarbeiro',
            name='servicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='barbeiro.servicos'),
        ),
    ]
