# Generated by Django 5.1 on 2024-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0006_remove_dadosbarbeiro_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbarbeiro',
            name='barbeiro_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
