# Generated by Django 5.1 on 2024-08-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0006_remove_dadosbarbeiro_servicos'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='barbeiro.servicos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('C', 'Cancelada')], default='A', max_length=1),
        ),
    ]
