# Generated by Django 5.1 on 2024-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_agendamentos_total_remove_agendamentos_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
